spring:
  profiles.active: default
msg: Hello world - this is from config server
---
spring:
  profiles: default
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/myappdb?autoReconnect=true
  username: root
  password: root
management:
  security:
    enabled: true
    role: ADMIN
---
spring:
  profiles: development 
spring.datasource:
  url: jdbc:mysql://qa.myapp.com:3306/myappdb?autoReconnect=true
  username: qauser
  password: qapasswo
---
spring:
  profiles: production
spring.datasource:
  url: jdbc:mysql://qa.myapp.com:3306/myappdb?autoReconnect=true
  username: qauser
  password: qapasso
